# **NUMPY: Arrays and Matrices**

**NumPy** is an extension to the Python programming language, adding support for large, multi-dimensional (numerical) arrays and matrices, along with a large library of high-level mathematical functions to operate on these arrays. NumPy is having the full form **"Numeric Python"**.

In [1]:
# Importing Required module
import numpy as np

## **Create arrays**

In [7]:
# create ndarrays from lists
# note: every element must be the same data type (will be converted is possible)
data1 = [1, 2, 3, 4, 5]        # list (all are interger data)
print(data1, len(data1), type(data1), id(data1))
arr1 = np.array(data1)         # 1-D array
print (arr1, type(arr1), len(arr1), id(arr1))

[1, 2, 3, 4, 5] 5 <class 'list'> 1829049031936
[1 2 3 4 5] <class 'numpy.ndarray'> 5 1829010777424


In [8]:
# create ndarrays from lists
# note: every element must be the same data type (will be converted is possible)
data1 = [1, 2.5, 3, 4, 5]      # list (mixed data types)
print(data1, len(data1), type(data1), id(data1))
arr1 = np.array(data1)         # 1-D array (converted to all float data)
print (arr1, type(arr1), len(arr1), id(arr1))

[1, 2.5, 3, 4, 5] 5 <class 'list'> 1829035517952
[1.  2.5 3.  4.  5. ] <class 'numpy.ndarray'> 5 1829014960336


In [9]:
# create ndarrays from lists
# note: every element must be the same data type (will be converted is possible)
data1 = [1, 2.5, "3", 4, 5]      # list (mixed data types)
print(data1, len(data1), type(data1), id(data1))
arr1 = np.array(data1)         # 1-D array (converted to all float data)
print (arr1, type(arr1), len(arr1), id(arr1))

[1, 2.5, '3', 4, 5] 5 <class 'list'> 1829049028608
['1' '2.5' '3' '4' '5'] <class 'numpy.ndarray'> 5 1829015557520


In [10]:
# create ndarrays from lists
# note: every element must be the same data type (will be converted is possible)
data1 = [1, 2, True, False, 3, 4, 5]      # list (mixed data types)
print(data1, len(data1), type(data1), id(data1))
arr1 = np.array(data1)         # 1-D array (converted to all float data)
print (arr1, type(arr1), len(arr1), id(arr1))

[1, 2, True, False, 3, 4, 5] 7 <class 'list'> 1829049198336
[1 2 1 0 3 4 5] <class 'numpy.ndarray'> 7 1829049162160


In [11]:
# create ndarrays from lists
# note: every element must be the same data type (will be converted is possible)
data1 = [1, 2, True, False, 3, 4.5, "5"]      # list (mixed data types)
print(data1, len(data1), type(data1), id(data1))
arr1 = np.array(data1)         # 1-D array (converted to all float data)
print (arr1, type(arr1), len(arr1), id(arr1))

[1, 2, True, False, 3, 4.5, '5'] 7 <class 'list'> 1829049114432
['1' '2' 'True' 'False' '3' '4.5' '5'] <class 'numpy.ndarray'> 7 1829014959280


In [50]:
print (list(range(1, 5)))             # range function creates a list
data2 = [range(1, 5), range(5, 9)]    # list of lists
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)                # 2-D array
print (data2, type(data2))
print (arr2, type(arr2))
for x in np.nditer(arr2):             # iterating over the ndarray
    print (x, end = ", ")

[1, 2, 3, 4]
[[1, 2, 3, 4], [5, 6, 7, 8]] <class 'list'>
[[1 2 3 4]
 [5 6 7 8]] <class 'numpy.ndarray'>
1, 2, 3, 4, 5, 6, 7, 8, 

In [17]:
list2 = arr2.tolist()                  # converting ndarray back to a list
print (list2, type(list2))
list2 = list(arr2)                     # converting ndarray back to a list
print (list2, type(list2))

[[1, 2, 3, 4], [5, 6, 7, 8]] <class 'list'>
[array([1, 2, 3, 4]), array([5, 6, 7, 8])] <class 'list'>


In [20]:
data1 = [1, 2, 3, 4, 5]        # list (all are interger data)
print(data1)
arr1 = np.array(data1)         # 1-D array
print (arr1)
list1 = list(arr1)
print(list1)
list1 = arr1.tolist()
print(list1)

[1, 2, 3, 4, 5]
[1 2 3 4 5]
[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]


In [24]:
# examining arrays
arr1 = np.array([11, 22, 33, 44, 55])
arr2 = np.array([[11, 22, 33, 44], [55, 66, 77, 88]])
print (arr1, type(arr1), id(arr1))
print (arr2, type(arr2), id(arr2))
print (arr1.dtype, arr2.dtype)         # data type of the array
print (arr1.shape, type(arr1.shape))   # shape of the array (5,) => Singleton notation
print (arr2.shape, type(arr2.shape))   # shape of the array (2, 4)
print (arr1.ndim, arr2.ndim)           # number of dimensions
print (arr1.size, arr2.size)           # total number of elements
print (len(arr1), len(arr2))           # returns the first dimension

[11 22 33 44 55] <class 'numpy.ndarray'> 1829073050128
[[11 22 33 44]
 [55 66 77 88]] <class 'numpy.ndarray'> 1829049160624
int32 int32
(5,) <class 'tuple'>
(2, 4) <class 'tuple'>
1 2
5 8
5 2


In [23]:
var = (5)
print (var, type(var))
var = (5,)
print (var, type(var))

5 <class 'int'>
(5,) <class 'tuple'>


In [26]:
# create special arrays
print (np.zeros(10))
print (np.zeros(10, dtype = np.int8))
print (np.zeros(10).astype(int))
print (np.zeros((3, 6)))
print (np.zeros((3, 6), int))
print (np.zeros((3, 6)).astype(int))
print (np.zeros(10) + 5)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [30]:
print (np.ones(10))
print (np.ones((3, 6)))
print (np.ones(10, int))
print (np.ones((3, 6), np.int8))
print (np.ones(10).astype(int))
print (np.ones((3, 6)).astype(int))
print (np.ones(10) + 4)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[1 1 1 1 1 1 1 1 1 1]
[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]
[1 1 1 1 1 1 1 1 1 1]
[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [33]:
print (np.linspace(0, 1, 5))  # 0 to 1 (inclusive) with 5 equi-distant points
print (np.linspace(0, 1, 6))

[0.   0.25 0.5  0.75 1.  ]
[0.  0.2 0.4 0.6 0.8 1. ]


In [38]:
print (np.logspace(0, 3, 4))  # 10^0 to 10^3 (inclusive) with 4 points
print (np.logspace(0, 3, 4, base = 2))  # 2^0 to 2^3 (inclusive) with 4 points

[   1.   10.  100. 1000.]
[1. 2. 4. 8.]


In [51]:
# arange is like range, except it returns an array (but not a list)
int_list = list(range(5))
print (int_list, type(int_list[0]), type(int_list))
int_array = np.arange(5)
print (int_array, int_array.dtype, type(int_array))
float_array = int_array.astype(float)
print (float_array, float_array.dtype, type(float_array))

[0, 1, 2, 3, 4] <class 'int'> <class 'list'>
[0 1 2 3 4] int32 <class 'numpy.ndarray'>
[0. 1. 2. 3. 4.] float64 <class 'numpy.ndarray'>


## **Reshaping**

In [43]:
matrix = np.arange(10, dtype = float)
print (matrix, matrix.dtype, type(matrix), matrix.shape)
matrix1 = matrix.reshape((2, 5))
print (matrix1, matrix1.dtype, type(matrix1), matrix1.shape)
matrix1 = matrix.reshape((2, -1))
print (matrix1, matrix1.dtype, type(matrix1), matrix1.shape)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.] float64 <class 'numpy.ndarray'> (10,)
[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]] float64 <class 'numpy.ndarray'> (2, 5)
[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]] float64 <class 'numpy.ndarray'> (2, 5)


In [44]:
matrix1 = matrix.reshape((2, 5)).astype(int)
print (matrix1, matrix1.dtype, type(matrix1), matrix1.shape)
matrix1 = matrix.astype(int).reshape((2, 5))
print (matrix1, matrix1.dtype, type(matrix1), matrix1.shape)

[[0 1 2 3 4]
 [5 6 7 8 9]] int32 <class 'numpy.ndarray'> (2, 5)
[[0 1 2 3 4]
 [5 6 7 8 9]] int32 <class 'numpy.ndarray'> (2, 5)


In [48]:
# transpose of a matrix
matrix = np.arange(10, dtype = float).reshape(2, 5)
print (matrix, matrix.dtype, type(matrix), matrix.shape)
matrix1 = matrix.T
print (matrix1, matrix1.dtype, type(matrix1), matrix1.shape)
matrix1 = matrix.transpose()
print (matrix1, matrix1.dtype, type(matrix1), matrix1.shape)

[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]] float64 <class 'numpy.ndarray'> (2, 5)
[[0. 5.]
 [1. 6.]
 [2. 7.]
 [3. 8.]
 [4. 9.]] float64 <class 'numpy.ndarray'> (5, 2)
[[0. 5.]
 [1. 6.]
 [2. 7.]
 [3. 8.]
 [4. 9.]] float64 <class 'numpy.ndarray'> (5, 2)


In [49]:
# transpose of a matrix
matrix = np.arange(10, dtype = float).reshape(2, 5)
print (matrix, matrix.dtype, type(matrix), matrix.shape)
matrix1 = matrix.flatten()
print (matrix1, matrix1.dtype, type(matrix1), matrix1.shape)

[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]] float64 <class 'numpy.ndarray'> (2, 5)
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.] float64 <class 'numpy.ndarray'> (10,)


In [53]:
matrix = np.arange(10, dtype = float).reshape((2, 5))
print (matrix)

print ('\nStored in C-style order (Row Major):')
cmatrix = matrix.copy(order = 'C')
print (cmatrix)
for x in np.nditer(cmatrix):
    print (x, end = ", ")
print ()

[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]

Stored in C-style order (Row Major):
[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 


In [54]:
matrix = np.arange(10, dtype = float).reshape((2, 5))
print (matrix)

print ('\nStored in F-style order (Column Major):')
fmatrix = matrix.copy(order = 'F')
print (fmatrix)
for x in np.nditer(fmatrix):
    print (x, end = ", ")

[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]

Stored in F-style order (Column Major):
[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
0.0, 5.0, 1.0, 6.0, 2.0, 7.0, 3.0, 8.0, 4.0, 9.0, 

## **Append, Insert, Delete and Sort**

In [55]:
matrix = np.arange(10, dtype = np.int8)
print (matrix, matrix.dtype, type(matrix), matrix.shape)
matrix = np.append(matrix, [10, 11, 12])
print (matrix, matrix.dtype, type(matrix), matrix.shape)
matrix = np.insert(matrix, 3, [13, 14, 15])
print (matrix, matrix.dtype, type(matrix), matrix.shape)

[0 1 2 3 4 5 6 7 8 9] int8 <class 'numpy.ndarray'> (10,)
[ 0  1  2  3  4  5  6  7  8  9 10 11 12] int32 <class 'numpy.ndarray'> (13,)
[ 0  1  2 13 14 15  3  4  5  6  7  8  9 10 11 12] int32 <class 'numpy.ndarray'> (16,)


In [60]:
matrix = np.arange(10, dtype = np.int8) + 100
print (matrix, matrix.dtype, type(matrix), matrix.shape)
matrix = np.delete(matrix, [5, 6, 7])
print (matrix, matrix.dtype, type(matrix), matrix.shape)

matrix = np.arange(10, dtype = np.int8) + 100
print (matrix, matrix.dtype, type(matrix), matrix.shape)
matrix = np.delete(matrix, range(5, 8))
print (matrix, matrix.dtype, type(matrix), matrix.shape)

[100 101 102 103 104 105 106 107 108 109] int8 <class 'numpy.ndarray'> (10,)
[100 101 102 103 104 108 109] int8 <class 'numpy.ndarray'> (7,)
[100 101 102 103 104 105 106 107 108 109] int8 <class 'numpy.ndarray'> (10,)
[100 101 102 103 104 108 109] int8 <class 'numpy.ndarray'> (7,)


In [64]:
matrix = np.array([200, 300, 100, 500, 450, 250, 900])
print (matrix, matrix.dtype, type(matrix), matrix.shape)
matrix = np.sort(matrix)    # sort in the ascending order
print (matrix, matrix.dtype, type(matrix), matrix.shape)
print()
matrix = np.array([200, 300, 100, 500, 450, 250, 900])
print (matrix, matrix.dtype, type(matrix), matrix.shape)
print (matrix, -matrix)
matrix = -np.sort(-matrix)    # sort in the descending order
print (matrix, matrix.dtype, type(matrix), matrix.shape)

[200 300 100 500 450 250 900] int32 <class 'numpy.ndarray'> (7,)
[100 200 250 300 450 500 900] int32 <class 'numpy.ndarray'> (7,)

[200 300 100 500 450 250 900] int32 <class 'numpy.ndarray'> (7,)
[200 300 100 500 450 250 900] [-200 -300 -100 -500 -450 -250 -900]
[900 500 450 300 250 200 100] int32 <class 'numpy.ndarray'> (7,)


In [71]:
arr1 = np.arange(10, 0, -1, dtype = float)
print (arr1)
arr1 = np.arange(10, 0, -1)
print (arr1)
arr1 = np.arange(100, 50, -5, dtype = float)
print (arr1)

[10.  9.  8.  7.  6.  5.  4.  3.  2.  1.]
[10  9  8  7  6  5  4  3  2  1]
[100.  95.  90.  85.  80.  75.  70.  65.  60.  55.]


## **Concatenation and Stack of 2 Arrays**

In [72]:
a = np.array([[1, 2], [3, 4]])
print('First array:')
print(a)
print('\n')

b = np.array([[5, 6], [7, 8]])
print('Second array:')
print(b)
print('\n')

First array:
[[1 2]
 [3 4]]


Second array:
[[5 6]
 [7 8]]




In [73]:
# both the arrays are of same dimensions
print('Joining the two arrays along axis 0:')
print(np.concatenate((a, b)))
print('\n')

Joining the two arrays along axis 0:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]




In [74]:
print('Joining the two arrays along axis 1:')
print(np.concatenate((a, b), axis = 1))

Joining the two arrays along axis 1:
[[1 2 5 6]
 [3 4 7 8]]


In [82]:
matrix = np.array([[100, 200, 300, 400]])
print (matrix, type(matrix), matrix.ndim, matrix.shape)
arr = matrix.reshape(-1)
print (arr, type(arr), arr.ndim, arr.shape)
arr = matrix.reshape(-1, 1, 4)
print (arr, type(arr), arr.ndim, arr.shape)
arr = matrix.reshape(1, 4, -1)
print (arr, type(arr), matrix.ndim, arr.shape)

[[100 200 300 400]] <class 'numpy.ndarray'> 2 (1, 4)
[100 200 300 400] <class 'numpy.ndarray'> 1 (4,)
[[[100 200 300 400]]] <class 'numpy.ndarray'> 3 (1, 1, 4)
[[[100]
  [200]
  [300]
  [400]]] <class 'numpy.ndarray'> 2 (1, 4, 1)


## **Selection**

In [84]:
# l to R 0  1  2  3  4
# R to L-5 -4 -3 -2 -1 
data1 = [1, 2, 3, 4, 5]        # list
arr1 = np.array(data1)         # 1-D array
print (arr1, type(arr1), arr1.dtype, arr1.shape)
print (arr1[0], arr1[-5])      # 0-th element (indexing like a list)
print (arr1[4], arr1[-1])
print (arr1[2:], arr1[:3])
print (arr1[::-1])

[1 2 3 4 5] <class 'numpy.ndarray'> int32 (5,)
1 1
5 5
[3 4 5] [1 2 3]
[5 4 3 2 1]


In [85]:
data2 = [range(1, 5), range(5, 9)]    # list of lists
arr2 = np.array(data2)                # 2-D array
print (arr2, type(arr2), arr2.dtype, arr2.shape)
print (arr2[1][2])                    # indexing
print (arr2[0, :], arr2[1, :])        # slicing
print (arr2[:, 2])
print (arr2[:, 1:4])                  # all rows and columns from 1 (inclusive) to 4 (exclusive)

[[1 2 3 4]
 [5 6 7 8]] <class 'numpy.ndarray'> int32 (2, 4)
7
[1 2 3 4] [5 6 7 8]
[3 7]
[[2 3 4]
 [6 7 8]]


## **Views and copies**

In [86]:
arr = np.arange(10)
print (arr, type(arr), arr.dtype, arr.shape)
print (arr[5:8])
arr[5:8] = 12       # all the pre-existing values at those index places will be over-written
print (arr)
arr_view = arr[5:8]   # creates a view of arr, not a copy
print (arr_view, type(arr_view), arr_view.dtype, arr_view.shape)
arr_view[:] = 13
print (arr_view)
print (arr)

[0 1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'> int32 (10,)
[5 6 7]
[ 0  1  2  3  4 12 12 12  8  9]
[12 12 12] <class 'numpy.ndarray'> int32 (3,)
[13 13 13]
[ 0  1  2  3  4 13 13 13  8  9]


In [88]:
arr = np.arange(10)
print (arr, type(arr), arr.dtype, arr.shape)
arr_copy = arr[5:8].copy()   # creates a copy of arr
print (arr_copy, type(arr_copy), arr_copy.dtype, arr_copy.shape)
arr_copy[:] = 14
arr[5:8] = 20
print (arr_copy)
print (arr)

[0 1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'> int32 (10,)
[5 6 7] <class 'numpy.ndarray'> int32 (3,)
[14 14 14]
[ 0  1  2  3  4 20 20 20  8  9]


## **Using boolean arrays**

In [91]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print (arr)
print (arr, arr > 5)
print (~(arr > 5))
print (arr[arr > 5], arr[~(arr > 5)])  # ~ denotes not or negation
print (arr % 2 == 0)
print (arr[arr % 2 == 0])

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9] [False False False False False  True  True  True  True]
[ True  True  True  True  True False False False False]
[6 7 8 9] [1 2 3 4 5]
[False  True False  True False  True False  True False]
[2 4 6 8]


In [95]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print (arr)
print ((arr > 3) & (arr < 8))
print (arr[(arr > 3) & (arr < 8)])
arr = np.arange(0, 61)
print (arr[(arr % 2 == 0) & (arr % 3 == 0)])

[1 2 3 4 5 6 7 8 9]
[False False False  True  True  True  True False False]
[4 5 6 7]
[ 0  6 12 18 24 30 36 42 48 54 60]


In [100]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob'])
print (names)
print (names == 'Bob')
print (~(names == 'Bob'))
print (names[names == 'Bob'])
print (names[names != 'Bob'])
print (names[~(names == 'Bob')])

['Bob' 'Joe' 'Will' 'Bob']
[ True False False  True]
[False  True  True False]
['Bob' 'Bob']
['Joe' 'Will']
['Joe' 'Will']


In [102]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob'])
print (names)
print (names[(names == 'Bob') | (names == 'Will')])  # don't use 'or' but use '|'
names[names != 'Bob'] = 'Tom'   # assign based on a logical selection
print (names)
print (np.unique(names))   

['Bob' 'Joe' 'Will' 'Bob']
['Bob' 'Will' 'Bob']
['Bob' 'Tom' 'Tom' 'Bob']
['Bob' 'Tom']


## **Vectorized operations**

In [104]:
nums = np.arange(5)
print (nums)
print (nums * 5)
print (nums + 5)
print (nums - 5)

[0 1 2 3 4]
[ 0  5 10 15 20]
[5 6 7 8 9]
[-5 -4 -3 -2 -1]


In [108]:
nums = np.arange(5)
print (nums)
nums = np.sqrt(nums)     # square root of each element
print (nums)       
print (np.ceil(nums))    # finding ceiling of each element
print (np.floor(nums))   # finding floor of each element

[0 1 2 3 4]
[0.         1.         1.41421356 1.73205081 2.        ]
[0. 1. 2. 2. 2.]
[0. 1. 1. 1. 2.]


In [110]:
nums = np.arange(5)
print (nums)
print (nums + np.arange(5)) # add element wise
print (np.isnan(nums))   # checks for NaN
nums = 2 * nums
print (nums)

[0 1 2 3 4]
[0 2 4 6 8]
[False False False False False]
[0 2 4 6 8]


In [112]:
nums = np.array([100, 200, np.nan, 400, np.nan, 500.5, 600])
print (nums)
print (np.isnan(nums))

[100.  200.    nan 400.    nan 500.5 600. ]
[False False  True False  True False False]


In [113]:
nums = np.arange(5)
print (nums)
print (np.max(nums), nums.max(), np.min(nums), nums.min())
print (np.maximum(nums, np.array([10, -2, 13, -4, 5]))) # compare element wise
print (np.minimum(nums, np.array([10, -2, 13, -4, 5])))

[0 1 2 3 4]
4 4 0 0
[10  1 13  3  5]
[ 0 -2  2 -4  4]


In [116]:
nums = np.arange(5)
print (nums)
nums_sqrt = np.sqrt(nums)
print (nums_sqrt)
print (np.round(nums_sqrt))

[0 1 2 3 4]
[0.         1.         1.41421356 1.73205081 2.        ]
[0. 1. 1. 2. 2.]


In [126]:
# calculating Euclidean distance between 2 vectors
vect1 = np.random.randn(10000)   # normalized random numbers, average and std near to 0 and 1 respectively
print (vect1, np.average(vect1), np.std(vect1))
vect2 = np.random.randn(10000)
print (vect2, np.average(vect2), np.std(vect2))

[-0.79469433  0.01892711 -0.20176553 ...  0.77311631 -2.15829403
 -2.06656362] -0.005973807341434795 0.9962271076610084
[-0.98988802 -0.22928973 -1.76647088 ... -0.36905065  1.09962835
 -0.77678337] -0.0189521286478691 1.0000774988037857


In [128]:
# calculating Euclidean distance between 2 vectors
vect1 = np.random.randn(10)   # normalized random numbers, average and std near to 0 and 1 respectively
print (vect1, np.average(vect1), np.std(vect1))
vect2 = np.random.randn(10)
print (vect2, np.average(vect2), np.std(vect2))
total = 0
for i in range(len(vect1)):
    total = total + (vect1[i] - vect2[i]) ** 2
print (np.sqrt(total))   # Calculation of Euclidean distance - 1

[-0.04778921  0.39578614 -0.36194329 -0.12494008 -0.04644492  0.97495054
  0.18837088  0.51386047 -2.32239726  0.16211762] -0.06684291145454643 0.8326401809846599
[ 1.39744697 -1.94473602  0.96405695  0.88718116  0.78200403 -0.6491348
  1.41217282  0.08703851  0.9669788   0.2014454 ] 0.4104453806506312 0.9887891907945355
5.116132152350262


In [129]:
# calculating Euclidean distance between 2 vectors
vect1 = np.random.randn(10)   # normalized random numbers, average and std near to 0 and 1 respectively
print (vect1, np.average(vect1), np.std(vect1))
vect2 = np.random.randn(10)
print (vect2, np.average(vect2), np.std(vect2))
print (np.sqrt(np.sum((vect1 - vect2) ** 2)))   # Calculation of Euclidean distance - 2

[-0.28148343 -0.52265631 -1.15321675  0.55157642 -0.23316515 -0.77077569
  0.41634576  1.90789051 -0.09676969 -0.3357457 ] -0.051800001611021426 0.8089286894351136
[ 0.53941985 -0.97709316 -1.39513919 -0.72685938  1.16230284  1.79071187
  1.06321331 -1.47759767 -0.17123886 -1.82145885] -0.20137392556451889 1.2055396120014292
5.017442183747418


In [ ]:
print (np.sqrt(np.sum(pow(np.subtract(vect1, vect2), 2))))   # Calculation of Euclidean distance

In [146]:
vec1 = np.random.rand(10)   # random numbers ranging from 0 to 1
print (vec1)

[0.9271453  0.81246349 0.60107148 0.94445001 0.57081427 0.42499183
 0.62254442 0.87322763 0.46059995 0.22625416]


In [153]:
# math and stats
rnd = np.random.randn(4, 2)
print (rnd)
print (rnd.mean())
print (rnd.std())
print (rnd.argmin(), rnd.argmax())       # index of the minimum and maximum elements
print (np.argmin(rnd), np.argmax(rnd))   # index of the minimum and maximum elements
print (rnd.sum(axis = 0))   # sum of columns
print (rnd.sum(axis = 1))   # sum of rows

[[ 0.50379274  0.99570759]
 [ 0.903596   -1.46562828]
 [ 0.31637774  2.05807713]
 [ 0.18372718  1.25516742]]
0.5938521904866398
0.9574371129205929
3 5
3 5
[1.90749366 2.84332387]
[ 1.49950033 -0.56203228  2.37445487  1.4388946 ]


In [155]:
# methods for boolean arrays
rnd = np.random.randn(4, 2)
print (rnd)
print (rnd > 0)
print ((rnd > 0).sum())      # counts the number of positive values
print ((rnd > 0).any())      # checks if any value is True
print ((rnd > 0).all())      # checks if all values are True

[[ 1.07196506  1.59654124]
 [ 0.56119564 -2.76188322]
 [-0.29799461 -0.92690711]
 [-0.55574561 -1.64612985]]
[[ True  True]
 [ True False]
 [False False]
 [False False]]
3
True
False


In [190]:
# random numbers
np.random.seed(900)             # set the seed value for the random number generation
nums = np.random.rand(2, 3)     # 2 x 3 matrix
print (nums)
nums = np.random.randn(10)      # random normals (mean with 0 and std with 1)
print (nums)
nums = np.random.randint(0, 2, 10)    # 10 randomly picked 0 or 1
print (nums)

[[0.43320153 0.30732793 0.54441845]
 [0.14987996 0.30845    0.60867465]]
[-0.28851846 -0.1524546  -0.77464191 -0.67697893  1.40744459  0.79039751
 -1.29806891 -1.8986072  -0.39431442 -0.81143484]
[0 0 0 0 0 1 0 1 0 0]


In [ ]:
# [[0.43320153 0.30732793 0.54441845]
#  [0.14987996 0.30845    0.60867465]]
# [-0.28851846 -0.1524546  -0.77464191 -0.67697893  1.40744459  0.79039751
#  -1.29806891 -1.8986072  -0.39431442 -0.81143484]
# [0 0 0 0 0 1 0 1 0 0]

In [194]:
nums = np.random.rand(2, 3)     # 2 x 3 matrix, outside of the cell seed has no effect
print (nums)

[[0.66500689 0.8519076  0.98793841]
 [0.82261282 0.51879161 0.78974035]]


## **Broadcasting**

In [195]:
a1 = np.array([[ 0,  0,  0],
               [10, 10, 10],
               [20, 20, 20],
               [30, 30, 30]])
print (a1, type(a1))
a2 = np.array([[0], [10], [20], [30]])
print (a2, type(a2))

b1 = np.array([[0, 1, 2],
               [0, 1, 2],
               [0, 1, 2],               
               [0, 1, 2]])
print (b1, type(b1))
b2 = np.array([0, 1, 2])
print (b2, type(b2))

[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]] <class 'numpy.ndarray'>
[[ 0]
 [10]
 [20]
 [30]] <class 'numpy.ndarray'>
[[0 1 2]
 [0 1 2]
 [0 1 2]
 [0 1 2]] <class 'numpy.ndarray'>
[0 1 2] <class 'numpy.ndarray'>


In [196]:
result = a1 + b1
print (result)

result = a1 + b2
print (result)

result = a2 + b1
print (result)

result = a2 + b2
print (result)

[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]
[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]
[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]
[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]
