# **NUMPY: Arrays and Matrices**

**NumPy** is an extension to the Python programming language, adding support for large, multi-dimensional (numerical) arrays and matrices, along with a large library of high-level mathematical functions to operate on these arrays. NumPy is having the full form **"Numeric Python"**.

In [1]:
# Importing Required module
import numpy as np

## **Create arrays**

In [7]:
# create ndarrays from lists
# note: every element must be the same data type (will be converted is possible)
data1 = [1, 2, 3, 4, 5]        # list (all are interger data)
print(data1, len(data1), type(data1), id(data1))
arr1 = np.array(data1)         # 1-D array
print (arr1, type(arr1), len(arr1), id(arr1))

[1, 2, 3, 4, 5] 5 <class 'list'> 1829049031936
[1 2 3 4 5] <class 'numpy.ndarray'> 5 1829010777424


In [8]:
# create ndarrays from lists
# note: every element must be the same data type (will be converted is possible)
data1 = [1, 2.5, 3, 4, 5]      # list (mixed data types)
print(data1, len(data1), type(data1), id(data1))
arr1 = np.array(data1)         # 1-D array (converted to all float data)
print (arr1, type(arr1), len(arr1), id(arr1))

[1, 2.5, 3, 4, 5] 5 <class 'list'> 1829035517952
[1.  2.5 3.  4.  5. ] <class 'numpy.ndarray'> 5 1829014960336


In [9]:
# create ndarrays from lists
# note: every element must be the same data type (will be converted is possible)
data1 = [1, 2.5, "3", 4, 5]      # list (mixed data types)
print(data1, len(data1), type(data1), id(data1))
arr1 = np.array(data1)         # 1-D array (converted to all float data)
print (arr1, type(arr1), len(arr1), id(arr1))

[1, 2.5, '3', 4, 5] 5 <class 'list'> 1829049028608
['1' '2.5' '3' '4' '5'] <class 'numpy.ndarray'> 5 1829015557520


In [10]:
# create ndarrays from lists
# note: every element must be the same data type (will be converted is possible)
data1 = [1, 2, True, False, 3, 4, 5]      # list (mixed data types)
print(data1, len(data1), type(data1), id(data1))
arr1 = np.array(data1)         # 1-D array (converted to all float data)
print (arr1, type(arr1), len(arr1), id(arr1))

[1, 2, True, False, 3, 4, 5] 7 <class 'list'> 1829049198336
[1 2 1 0 3 4 5] <class 'numpy.ndarray'> 7 1829049162160


In [11]:
# create ndarrays from lists
# note: every element must be the same data type (will be converted is possible)
data1 = [1, 2, True, False, 3, 4.5, "5"]      # list (mixed data types)
print(data1, len(data1), type(data1), id(data1))
arr1 = np.array(data1)         # 1-D array (converted to all float data)
print (arr1, type(arr1), len(arr1), id(arr1))

[1, 2, True, False, 3, 4.5, '5'] 7 <class 'list'> 1829049114432
['1' '2' 'True' 'False' '3' '4.5' '5'] <class 'numpy.ndarray'> 7 1829014959280


In [50]:
print (list(range(1, 5)))             # range function creates a list
data2 = [range(1, 5), range(5, 9)]    # list of lists
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)                # 2-D array
print (data2, type(data2))
print (arr2, type(arr2))
for x in np.nditer(arr2):             # iterating over the ndarray
    print (x, end = ", ")

[1, 2, 3, 4]
[[1, 2, 3, 4], [5, 6, 7, 8]] <class 'list'>
[[1 2 3 4]
 [5 6 7 8]] <class 'numpy.ndarray'>
1, 2, 3, 4, 5, 6, 7, 8, 

In [17]:
list2 = arr2.tolist()                  # converting ndarray back to a list
print (list2, type(list2))
list2 = list(arr2)                     # converting ndarray back to a list
print (list2, type(list2))

[[1, 2, 3, 4], [5, 6, 7, 8]] <class 'list'>
[array([1, 2, 3, 4]), array([5, 6, 7, 8])] <class 'list'>


In [20]:
data1 = [1, 2, 3, 4, 5]        # list (all are interger data)
print(data1)
arr1 = np.array(data1)         # 1-D array
print (arr1)
list1 = list(arr1)
print(list1)
list1 = arr1.tolist()
print(list1)

[1, 2, 3, 4, 5]
[1 2 3 4 5]
[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]


In [24]:
# examining arrays
arr1 = np.array([11, 22, 33, 44, 55])
arr2 = np.array([[11, 22, 33, 44], [55, 66, 77, 88]])
print (arr1, type(arr1), id(arr1))
print (arr2, type(arr2), id(arr2))
print (arr1.dtype, arr2.dtype)         # data type of the array
print (arr1.shape, type(arr1.shape))   # shape of the array (5,) => Singleton notation
print (arr2.shape, type(arr2.shape))   # shape of the array (2, 4)
print (arr1.ndim, arr2.ndim)           # number of dimensions
print (arr1.size, arr2.size)           # total number of elements
print (len(arr1), len(arr2))           # returns the first dimension

[11 22 33 44 55] <class 'numpy.ndarray'> 1829073050128
[[11 22 33 44]
 [55 66 77 88]] <class 'numpy.ndarray'> 1829049160624
int32 int32
(5,) <class 'tuple'>
(2, 4) <class 'tuple'>
1 2
5 8
5 2


In [23]:
var = (5)
print (var, type(var))
var = (5,)
print (var, type(var))

5 <class 'int'>
(5,) <class 'tuple'>


In [26]:
# create special arrays
print (np.zeros(10))
print (np.zeros(10, dtype = np.int8))
print (np.zeros(10).astype(int))
print (np.zeros((3, 6)))
print (np.zeros((3, 6), int))
print (np.zeros((3, 6)).astype(int))
print (np.zeros(10) + 5)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [30]:
print (np.ones(10))
print (np.ones((3, 6)))
print (np.ones(10, int))
print (np.ones((3, 6), np.int8))
print (np.ones(10).astype(int))
print (np.ones((3, 6)).astype(int))
print (np.ones(10) + 4)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[1 1 1 1 1 1 1 1 1 1]
[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]
[1 1 1 1 1 1 1 1 1 1]
[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [33]:
print (np.linspace(0, 1, 5))  # 0 to 1 (inclusive) with 5 equi-distant points
print (np.linspace(0, 1, 6))

[0.   0.25 0.5  0.75 1.  ]
[0.  0.2 0.4 0.6 0.8 1. ]


In [38]:
print (np.logspace(0, 3, 4))  # 10^0 to 10^3 (inclusive) with 4 points
print (np.logspace(0, 3, 4, base = 2))  # 2^0 to 2^3 (inclusive) with 4 points

[   1.   10.  100. 1000.]
[1. 2. 4. 8.]


In [51]:
# arange is like range, except it returns an array (but not a list)
int_list = list(range(5))
print (int_list, type(int_list[0]), type(int_list))
int_array = np.arange(5)
print (int_array, int_array.dtype, type(int_array))
float_array = int_array.astype(float)
print (float_array, float_array.dtype, type(float_array))

[0, 1, 2, 3, 4] <class 'int'> <class 'list'>
[0 1 2 3 4] int32 <class 'numpy.ndarray'>
[0. 1. 2. 3. 4.] float64 <class 'numpy.ndarray'>


## **Reshaping**

In [43]:
matrix = np.arange(10, dtype = float)
print (matrix, matrix.dtype, type(matrix), matrix.shape)
matrix1 = matrix.reshape((2, 5))
print (matrix1, matrix1.dtype, type(matrix1), matrix1.shape)
matrix1 = matrix.reshape((2, -1))
print (matrix1, matrix1.dtype, type(matrix1), matrix1.shape)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.] float64 <class 'numpy.ndarray'> (10,)
[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]] float64 <class 'numpy.ndarray'> (2, 5)
[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]] float64 <class 'numpy.ndarray'> (2, 5)


In [44]:
matrix1 = matrix.reshape((2, 5)).astype(int)
print (matrix1, matrix1.dtype, type(matrix1), matrix1.shape)
matrix1 = matrix.astype(int).reshape((2, 5))
print (matrix1, matrix1.dtype, type(matrix1), matrix1.shape)

[[0 1 2 3 4]
 [5 6 7 8 9]] int32 <class 'numpy.ndarray'> (2, 5)
[[0 1 2 3 4]
 [5 6 7 8 9]] int32 <class 'numpy.ndarray'> (2, 5)


In [48]:
# transpose of a matrix
matrix = np.arange(10, dtype = float).reshape(2, 5)
print (matrix, matrix.dtype, type(matrix), matrix.shape)
matrix1 = matrix.T
print (matrix1, matrix1.dtype, type(matrix1), matrix1.shape)
matrix1 = matrix.transpose()
print (matrix1, matrix1.dtype, type(matrix1), matrix1.shape)

[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]] float64 <class 'numpy.ndarray'> (2, 5)
[[0. 5.]
 [1. 6.]
 [2. 7.]
 [3. 8.]
 [4. 9.]] float64 <class 'numpy.ndarray'> (5, 2)
[[0. 5.]
 [1. 6.]
 [2. 7.]
 [3. 8.]
 [4. 9.]] float64 <class 'numpy.ndarray'> (5, 2)


In [49]:
# transpose of a matrix
matrix = np.arange(10, dtype = float).reshape(2, 5)
print (matrix, matrix.dtype, type(matrix), matrix.shape)
matrix1 = matrix.flatten()
print (matrix1, matrix1.dtype, type(matrix1), matrix1.shape)

[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]] float64 <class 'numpy.ndarray'> (2, 5)
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.] float64 <class 'numpy.ndarray'> (10,)


In [53]:
matrix = np.arange(10, dtype = float).reshape((2, 5))
print (matrix)

print ('\nStored in C-style order (Row Major):')
cmatrix = matrix.copy(order = 'C')
print (cmatrix)
for x in np.nditer(cmatrix):
    print (x, end = ", ")
print ()

[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]

Stored in C-style order (Row Major):
[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 


In [54]:
matrix = np.arange(10, dtype = float).reshape((2, 5))
print (matrix)

print ('\nStored in F-style order (Column Major):')
fmatrix = matrix.copy(order = 'F')
print (fmatrix)
for x in np.nditer(fmatrix):
    print (x, end = ", ")

[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]

Stored in F-style order (Column Major):
[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
0.0, 5.0, 1.0, 6.0, 2.0, 7.0, 3.0, 8.0, 4.0, 9.0, 

## **Append, Insert, Delete and Sort**

In [55]:
matrix = np.arange(10, dtype = np.int8)
print (matrix, matrix.dtype, type(matrix), matrix.shape)
matrix = np.append(matrix, [10, 11, 12])
print (matrix, matrix.dtype, type(matrix), matrix.shape)
matrix = np.insert(matrix, 3, [13, 14, 15])
print (matrix, matrix.dtype, type(matrix), matrix.shape)

[0 1 2 3 4 5 6 7 8 9] int8 <class 'numpy.ndarray'> (10,)
[ 0  1  2  3  4  5  6  7  8  9 10 11 12] int32 <class 'numpy.ndarray'> (13,)
[ 0  1  2 13 14 15  3  4  5  6  7  8  9 10 11 12] int32 <class 'numpy.ndarray'> (16,)


In [60]:
matrix = np.arange(10, dtype = np.int8) + 100
print (matrix, matrix.dtype, type(matrix), matrix.shape)
matrix = np.delete(matrix, [5, 6, 7])
print (matrix, matrix.dtype, type(matrix), matrix.shape)

matrix = np.arange(10, dtype = np.int8) + 100
print (matrix, matrix.dtype, type(matrix), matrix.shape)
matrix = np.delete(matrix, range(5, 8))
print (matrix, matrix.dtype, type(matrix), matrix.shape)

[100 101 102 103 104 105 106 107 108 109] int8 <class 'numpy.ndarray'> (10,)
[100 101 102 103 104 108 109] int8 <class 'numpy.ndarray'> (7,)
[100 101 102 103 104 105 106 107 108 109] int8 <class 'numpy.ndarray'> (10,)
[100 101 102 103 104 108 109] int8 <class 'numpy.ndarray'> (7,)


In [64]:
matrix = np.array([200, 300, 100, 500, 450, 250, 900])
print (matrix, matrix.dtype, type(matrix), matrix.shape)
matrix = np.sort(matrix)    # sort in the ascending order
print (matrix, matrix.dtype, type(matrix), matrix.shape)
print()
matrix = np.array([200, 300, 100, 500, 450, 250, 900])
print (matrix, matrix.dtype, type(matrix), matrix.shape)
print (matrix, -matrix)
matrix = -np.sort(-matrix)    # sort in the descending order
print (matrix, matrix.dtype, type(matrix), matrix.shape)

[200 300 100 500 450 250 900] int32 <class 'numpy.ndarray'> (7,)
[100 200 250 300 450 500 900] int32 <class 'numpy.ndarray'> (7,)

[200 300 100 500 450 250 900] int32 <class 'numpy.ndarray'> (7,)
[200 300 100 500 450 250 900] [-200 -300 -100 -500 -450 -250 -900]
[900 500 450 300 250 200 100] int32 <class 'numpy.ndarray'> (7,)


In [71]:
arr1 = np.arange(10, 0, -1, dtype = float)
print (arr1)
arr1 = np.arange(10, 0, -1)
print (arr1)
arr1 = np.arange(100, 50, -5, dtype = float)
print (arr1)


[10.  9.  8.  7.  6.  5.  4.  3.  2.  1.]
[10  9  8  7  6  5  4  3  2  1]
[100.  95.  90.  85.  80.  75.  70.  65.  60.  55.]


## **Concatenation and Stack of 2 Arrays**

In [65]:
a=np.array([[1, 2], [3, 4]])
print ('First array:')
print (a)
print ('\n')

b = np.array([[5, 6], [7, 8]])
print ('Second array:')
print (b)
print ('\n')

First array:
[[1 2]
 [3 4]]


Second array:
[[5 6]
 [7 8]]




In [66]:
# both the arrays are of same dimensions
print ('Joining the two arrays along axis 0:')
print (np.concatenate((a, b)))
print ('\n')

Joining the two arrays along axis 0:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]




In [67]:
print ('Joining the two arrays along axis 1:')
print (np.concatenate((a, b), axis=1))

Joining the two arrays along axis 1:
[[1 2 5 6]
 [3 4 7 8]]
