# **PANDAS: INTRODUCTION**
> It is often said that 80% of data analysis is spent on the data cleaning and preparing data. To get a handle on the problem, this section focuses on a small, but important aspect of data manipulation and cleaning with Pandas.
## **Data Structures**
**There are two data structures are there in Pandas -**<br>
* **Series -** It is one-dimensional labeled array capable of holding any data type (integer, strings, floating point numbers, Python objects etc.) of data. The axis is collectively referred to as index.

* **Data Frame -** It is a two-dimensional labeled data structure with columns of potentially different types. You can think of it like a spreadsheet or SQL Table or a Series of objects.

## **Series Data Structure:**
**pandas.core.series.Series(data, index, dtype, copy)**<br>
* **data -** data takes various forms like ndarray, list, constants, dictionary etc.<br>
* **index -** it is unique and hashable for easy identification.<br>
* **dtype -** it is for data type.<br>
* **copy -** copy data, and its default value is False. It only affects for Series or one dimensional ndarray inputs.

In [1]:
# importing required modules
import pandas as pd
import numpy as np

In [3]:
# creating empty Series
import warnings
warnings.filterwarnings('ignore')
s = pd.Series()
print (s, type(s))

Series([], dtype: float64) <class 'pandas.core.series.Series'>


In [5]:
# create a Series from a ndarray
arr_data = np.array(['apple', 'banana', 'cherry', 'pineapple'])
print (arr_data, type(arr_data))
s = pd.Series(data = arr_data)
print (s)
print (type(s), s[0], s[3])

['apple' 'banana' 'cherry' 'pineapple'] <class 'numpy.ndarray'>
0        apple
1       banana
2       cherry
3    pineapple
dtype: object
<class 'pandas.core.series.Series'> apple pineapple


In [6]:
arr_data = np.array([100, 300, 200, 600, 500])
s = pd.Series(data = arr_data, copy = False)
print (arr_data)
print (s)
s[0] = 999; arr_data[2] = 888
print (arr_data)
print (s)

[100 300 200 600 500]
0    100
1    300
2    200
3    600
4    500
dtype: int32
[999 300 888 600 500]
0    999
1    300
2    888
3    600
4    500
dtype: int32


In [7]:
arr_data = np.array([100, 300, 200, 600, 500])
s = pd.Series(data = arr_data, copy = True)
print (arr_data)
print (s)
s[0] = 999; arr_data[2] = 888
print (arr_data)
print (s)

[100 300 200 600 500]
0    100
1    300
2    200
3    600
4    500
dtype: int32
[100 300 888 600 500]
0    999
1    300
2    200
3    600
4    500
dtype: int32


In [9]:
arr_data = np.array(['apple', 'banana', 'cherry', 'pineapple'])
print (arr_data, type(arr_data))
s = pd.Series(data = arr_data)
print (s)
s = pd.Series(data = arr_data, index = [100, 101, 102, 103])
print (s)
print (s[100], type(s[100]), s[103], type(s[103]))

['apple' 'banana' 'cherry' 'pineapple'] <class 'numpy.ndarray'>
0        apple
1       banana
2       cherry
3    pineapple
dtype: object
100        apple
101       banana
102       cherry
103    pineapple
dtype: object
apple <class 'str'> pineapple <class 'str'>


In [16]:
arr_data = np.array(['apple', 'banana', 'cherry', 'pineapple'])
print (arr_data, type(arr_data))
s = pd.Series(data = arr_data, index = [100, 101, 100, 103])
print (s)
print (s[100], type(s[100]), s[103], type(s[103]))
s[100] = 'lemon'
print (s)
print (s[100])

['apple' 'banana' 'cherry' 'pineapple'] <class 'numpy.ndarray'>
100        apple
101       banana
100       cherry
103    pineapple
dtype: object
100     apple
100    cherry
dtype: object <class 'pandas.core.series.Series'> pineapple <class 'str'>
100        lemon
101       banana
100        lemon
103    pineapple
dtype: object
100    lemon
100    lemon
dtype: object


In [14]:
arr_data = np.array(['apple', 'banana', 'cherry', 'pineapple'])
print (arr_data)
s = pd.Series(data = arr_data, index = ['fruit-1', 'fruit-2', 'fruit-3', 'fruit-4'])
print (s)
print (s['fruit-1'], s[0], s['fruit-3'], s[2])

['apple' 'banana' 'cherry' 'pineapple']
fruit-1        apple
fruit-2       banana
fruit-3       cherry
fruit-4    pineapple
dtype: object
apple apple cherry cherry


In [19]:
# create a Series from a dictionary
dict_data = {'apple':100, 'banana':202, 'coconut':450, 'mango':435}
print (dict_data)
s = pd.Series(data = dict_data)
print (s)
s = pd.Series(dict_data, index = ['banana', 'mango', 'apple', 'coconut'])

{'apple': 100, 'banana': 202, 'coconut': 450, 'mango': 435}
apple      100
banana     202
coconut    450
mango      435
dtype: int64


In [23]:
dict_data = {'apple':100, 'banana':202, 'coconut':450, 'mango':435}
s = pd.Series(dict_data, index = ['banana', 'mango', 'apple', 'coconut'])
print (s)
s = pd.Series(data = dict_data, index = ['banana', 'lime', 'coconut', 'mango', 
                                         'guava', 'apple', 'mango', 'apple', 'coconut'])
print (s)
print (s['banana'], s['lime'], s[4], s[5])

banana     202
mango      435
apple      100
coconut    450
dtype: int64
banana     202.0
lime         NaN
coconut    450.0
mango      435.0
guava        NaN
apple      100.0
mango      435.0
apple      100.0
coconut    450.0
dtype: float64
202.0 nan nan 100.0


In [25]:
# create a Series from a scalar
s = pd.Series(data = 5, index = [0, 1, 2, 3, 4])
print (s)
s = pd.Series(5, index = [0, 1, 2, 0, 1, 2])
print (s)

0    5
1    5
2    5
3    5
4    5
dtype: int64
0    5
1    5
2    5
0    5
1    5
2    5
dtype: int64


In [27]:
# Create a Series from a list
s = pd.Series(data = [101, 303, 202, 404, 505], index = ['red', 'blue', 'brown', 'black', 'silver'])
print (s)
print (s['blue'], s[1])
print (s[0:4])
print (s[-5:-1])
print (s[['brown', 'red', 'silver', 'blue']])

red       101
blue      303
brown     202
black     404
silver    505
dtype: int64
303 303
red      101
blue     303
brown    202
black    404
dtype: int64
red      101
blue     303
brown    202
black    404
dtype: int64
brown     202
red       101
silver    505
blue      303
dtype: int64


In [30]:
print (s)
print (s.sort_values())
print (s.sort_index())

red       101
blue      303
brown     202
black     404
silver    505
dtype: int64
red       101
brown     202
blue      303
black     404
silver    505
dtype: int64
black     404
blue      303
brown     202
red       101
silver    505
dtype: int64


In [34]:
print (s)
print (s.argmin(), s.argmax(), s.count(), len(s))

red       101
blue      303
brown     202
black     404
silver    505
dtype: int64
0 4 5 5


## **Data Frame Data Structure:**